# NBA Game Outcome/Score Prediction - Data Exploration

## Project Objective
The Objective of this project is to use historical NBA game statistics to predict whether the home team will win a game.

We will also investigate the feasibility of predicting final scores and point differentials using regression models.

## Dataset

Source: Wyatt walsh NBA Database (Kaggle)
https://www.kaggle.com/datasets/wyattowalsh/basketball

This notebook explores the dataset's structure, features, missing values, and relationships between variables

### Import libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

### Load data

In [2]:
df = pd.read_csv("../data/game.csv")
print("Dataset loaded successfully!")

Dataset loaded successfully!

### Display first rows

In [3]:
display(df.head())

,season_id,team_id_home,team_abbreviation_home,team_name_home,game_id,game_date,matchup_home,wl_home,min,fgm_home,...,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,plus_minus_away,video_available_away,season_type
0,21946,1610610035,HUS,Toronto Huskies,24600001,1946-11-01 00:00:00,HUS vs. NYK,L,0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,68.0,2,0,Regular Season
1,21946,1610610034,BOM,St. Louis Bombers,24600003,1946-11-02 00:00:00,BOM vs. PIT,W,0,20.0,...,NaN,NaN,NaN,NaN,NaN,25.0,51.0,-5,0,Regular Season
2,21946,1610610032,PRO,Providence Steamrollers,24600002,1946-11-02 00:00:00,PRO vs. BOS,W,0,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,53.0,-6,0,Regular Season
3,21946,1610610025,CHS,Chicago Stags,24600004,1946-11-02 00:00:00,CHS vs. NYK,W,0,21.0,...,NaN,NaN,NaN,NaN,NaN,22.0,47.0,-16,0,Regular Season
4,21946,1610610028,DEF,Detroit Falcons,24600005,1946-11-02 00:00:00,DEF vs. WAS,L,0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,50.0,17,0,Regular Season

### Dataset Dimensions

In [4]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 65698
Number of columns: 55

### Column names and data types

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 65698 entries, 0 to 65697
Data columns (total 55 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   season_id               65698 non-null  int64
 1   team_id_home            65698 non-null  int64
 2   team_abbreviation_home  65698 non-null  str
 3   team_name_home          65698 non-null  str
 4   game_id                 65698 non-null  int64
 5   game_date               65698 non-null  str
 6   matchup_home            65698 non-null  str
 7   wl_home                 65696 non-null  str
 8   min                     65698 non-null  int64
 9   fgm_home                65685 non-null  float64
 10  fga_home                50251 non-null  float64
 11  fg_pct_home             50208 non-null  float64
 12  fg3m_home               52480 non-null  float64
 13  fg3a_home               47015 non-null  float64
 14  fg3_pct_home            46624 non-null  float64
 15  ftm_home                65682 non-null  float64
 16  fta_home                62694 non-null  float64
 17  ft_pct_home             62689 non-null  float64
 18  oreb_home               46762 non-null  float64
 19  dreb_home               46699 non-null  float64
 20  reb_home                49969 non-null  float64
 21  ast_home                49893 non-null  float64
 22  stl_home                46849 non-null  float64
 23  blk_home                47072 non-null  float64
 24  tov_home                47014 non-null  float64
 25  pf_home                 62842 non-null  float64
 26  pts_home                65698 non-null  float64
 27  plus_minus_home         65698 non-null  int64
 28  video_available_home    65698 non-null  int64
 29  team_id_away            65698 non-null  int64
 30  team_abbreviation_away  65698 non-null  str
 31  team_name_away          65698 non-null  str
 32  matchup_away            65698 non-null  str
 33  wl_away                 65696 non-null  str
 34  fgm_away                65685 non-null  float64
 35  fga_away                50251 non-null  float64
 36  fg_pct_away             50209 non-null  float64
 37  fg3m_away               52480 non-null  float64
 38  fg3a_away               47015 non-null  float64
 39  fg3_pct_away            46736 non-null  float64
 40  ftm_away                65685 non-null  float64
 41  fta_away                62694 non-null  float64
 42  ft_pct_away             62692 non-null  float64
 43  oreb_away               46762 non-null  float64
 44  dreb_away               46700 non-null  float64
 45  reb_away                49973 non-null  float64
 46  ast_away                49897 non-null  float64
 47  stl_away                46849 non-null  float64
 48  blk_away                47073 non-null  float64
 49  tov_away                47013 non-null  float64
 50  pf_away                 62847 non-null  float64
 51  pts_away                65698 non-null  float64
 52  plus_minus_away         65698 non-null  int64
 53  video_available_away    65698 non-null  int64
 54  season_type             65698 non-null  str
dtypes: float64(36), int64(9), str(10)
memory usage: 33.4 MB

### Summary Statistics

In [7]:
display(df.describe())

,season_id,team_id_home,game_id,min,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,...,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,plus_minus_away,video_available_away
count,65698.000000,6.569800e+04,6.569800e+04,65698.000000,65685.000000,50251.000000,50208.000000,52480.000000,47015.000000,46624.000000,...,46700.000000,49973.000000,49897.000000,46849.000000,47073.000000,47013.000000,62847.000000,65698.000000,65698.000000,65698.000000
mean,22949.338747,1.609926e+09,2.584747e+07,221.003486,39.672269,83.992796,0.467321,5.735099,17.741146,0.346136,...,30.238073,42.119645,22.135419,7.854148,4.681537,15.199860,23.097284,100.991567,-3.627569,0.201330
std,5000.305500,3.324313e+07,6.303760e+06,67.903521,6.770802,9.164445,0.059423,4.537337,10.545810,0.151234,...,5.588675,6.867396,5.380805,3.031766,2.500820,4.299798,5.227208,14.418755,13.091395,0.400997
min,12005.000000,4.500000e+01,1.050000e+07,0.000000,4.000000,0.000000,0.140000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,19.000000,-73.000000,0.000000
25%,21981.000000,1.610613e+09,2.130053e+07,240.000000,35.000000,78.000000,0.427000,2.000000,10.000000,0.261000,...,26.000000,37.000000,18.000000,6.000000,3.000000,12.000000,20.000000,92.000000,-12.000000,0.000000
50%,21997.000000,1.610613e+09,2.630007e+07,240.000000,40.000000,84.000000,0.467000,5.000000,16.000000,0.348000,...,30.000000,42.000000,22.000000,8.000000,4.000000,15.000000,23.000000,101.000000,-4.000000,0.000000
75%,22011.000000,1.610613e+09,2.880069e+07,240.000000,44.000000,89.000000,0.506000,9.000000,24.000000,0.429750,...,34.000000,47.000000,26.000000,10.000000,6.000000,18.000000,26.000000,110.000000,5.000000,0.000000
max,42022.000000,1.610617e+09,4.980009e+07,365.000000,84.000000,240.000000,0.697000,28.000000,77.000000,1.000000,...,60.000000,90.000000,89.000000,27.000000,19.000000,40.000000,115.000000,196.000000,68.000000,1.000000

### Missing values

In [9]:
missing = df.isnull().sum()
print("Missing count:\n", missing)

Missing count:
 season_id                     0
team_id_home                  0
team_abbreviation_home        0
team_name_home                0
game_id                       0
game_date                     0
matchup_home                  0
wl_home                       2
min                           0
fgm_home                     13
fga_home                  15447
fg_pct_home               15490
fg3m_home                 13218
fg3a_home                 18683
fg3_pct_home              19074
ftm_home                     16
fta_home                   3004
ft_pct_home                3009
oreb_home                 18936
dreb_home                 18999
reb_home                  15729
ast_home                  15805
stl_home                  18849
blk_home                  18626
tov_home                  18684
pf_home                    2856
pts_home                      0
plus_minus_home               0
video_available_home          0
team_id_away                  0
team_abbreviation_away        0
team_name_away                0
matchup_away                  0
wl_away                       2
fgm_away                     13
fga_away                  15447
fg_pct_away               15489
fg3m_away                 13218
fg3a_away                 18683
fg3_pct_away              18962
ftm_away                     13
fta_away                   3004
ft_pct_away                3006
oreb_away                 18936
dreb_away                 18998
reb_away                  15725
ast_away                  15801
stl_away                  18849
blk_away                  18625
tov_away                  18685
pf_away                    2851
pts_away                      0
plus_minus_away               0
video_available_away          0
season_type                   0
dtype: int64

In [10]:
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0